version: '3.0'

services:
  web:
    container_name: ui-neo
    image: ivoin/ui-neo
    build:
      context: ./ui/
    volumes:
      - ./ui/src/public
      - ./ui/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    restart: always
  server:
    container_name: server-neo
    image: ivoin/server-neo
    build:
      context: ./server/
    env_file:
      - ./server/.dev.env
    volumes:
      - ./server/src/app
      - ./server/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - mariadb
    restart: always
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neoflex_portal
      MYSQL_USER: root
      MYSQL_PASSWORD: root
